[env]
RUST_BACKTRACE = "full"

[tasks.clean]
description = "Clean target directory"
command = "cargo"
args = ["clean"]

[tasks.build]
description = "Run cargo build"
command = "cargo"
args = ["build", "--workspace", "@@split(FEATURES_FLAG, )"]

[tasks.fmt]
condition = { channels = ["nightly"] }
description = "Check whether rust code is properly formatted or not"
command = "cargo"
args = ["fmt", "--", "--check"]

[tasks.clippy]
condition = { channels = ["nightly"] }
description = "Check if clippy return any warnings or error"
command = "cargo"
args = [
    "clippy",
    "--workspace",
    "@@split(FEATURES_FLAG, )",
    "--",
    "-D",
    "warnings",
]

[tasks.test]
description = "Run test"
command = "cargo"
args = ["test", "--workspace", "@@split(FEATURES_FLAG, )"]

[tasks.doc]
description = "Run doc"
command = "cargo"
args = ["doc", "--workspace", "--no-deps", "@@split(FEATURES_FLAG, )"]

[tasks.rustdoc]
description = "Run rustdoc"
command = "cargo"
args = ["rustdoc", "--all-features", "--", "--cfg", "docsrs"]

[tasks.local]
dependencies = ["fmt", "build", "clippy", "doc", "test"]

[tasks.full]
dependencies = ["clean", "local"]

[tasks.run_postgres_example]
description = "run postgres example"
command = "cargo"
args = ["run", "--example", "postgres", "--features", "postgres", "--", "${@}"]

[tasks.run_sqlite_example]
description = "run postgres example"
command = "cargo"
args = ["run", "--example", "sqlite", "--features", "sqlite", "--", "${@}"]

[tasks.run_mysql_example]
description = "run postgres example"
command = "cargo"
args = ["run", "--example", "mysql", "--features", "mysql", "--", "${@}"]
